export const BRAND_THEME = {
  brandName: "Iggymet",
  logoReference: {
    fileName: "WhatsApp_Image_2026-04-04_at_11.41.58_AM-removebg-preview.png",
    sourcePath:
      "C:/Users/aditi/Downloads/WhatsApp_Image_2026-04-04_at_11.41.58_AM-removebg-preview.png",
  },
  colors: {
    brand: {
      primary: "#FF6A00",
      primaryDark: "#E05E00",
      primarySoft: "#FFF1E6",
      accentGreen: "#FF8A33",
      accentGreenSoft: "#FFF6EF",
      midnight: "#003322",
    },
    semantic: {
      success: "#16A34A",
      successDark: "#15803D",
      successSoft: "#F0FDF4",
      veg: "#16A34A",
      vegDark: "#15803D",
      vegSoft: "#F0FDF4",
      warning: "#F59E0B",
      error: "#DC2626",
    },
    neutral: {
      textPrimary: "#1A2421",
      textSecondary: "#4A5D57",
      textMuted: "#71837D",
      surface: "#FFFFFF",
      surfaceAlt: "#F9FAF9",
      surfaceMuted: "#F1F3F1",
      border: "#E2E8E2",
      borderSoft: "#EDF2ED",
      black: "#000000",
      white: "#FFFFFF",
    },
    legacy: {
      oldPrimaryOrange: "#EB590E",
      oldAccentOrange: "#F6881F",
      oldSoftOrange: "#FFF2EB",
      oldHoverOrange: "#D94F0C",
    },
  },
  tokens: {
    app: {
      pageBackground: "#FFFFFF",
      cardBackground: "#FFFFFF",
      sectionBackground: "#FFFFFF",
      sectionAltBackground: "#F1F3F1",
      primaryText: "#1A2421",
      secondaryText: "#4A5D57",
      mutedText: "#71837D",
      border: "#E2E8E2",
    },
    header: {
      defaultBackground: "transparent",
      scrolledBackground: "#FFFFFF",
      searchBackground: "#FFFFFF",
      searchIcon: "#FF6A00",
    },
    button: {
      primaryBackground: "#FF6A00",
      primaryHover: "#E05E00",
      primaryText: "#FFFFFF",
      accentBackground: "#E05E00",
      accentHover: "#003322",
      accentText: "#FFFFFF",
    },
    footer: {
      background: "#E05E00",
      surfaceText: "#FFF1E6",
      mutedText: "#71837D",
      sectionHeading: "#16A34A",
      brandGradient: "linear-gradient(135deg, #FF6A00 0%, #E05E00 100%)",
      divider: "#1A2421",
    },
    location: {
      icon: "#FF6A00",
      iconSoft: "#FFF1E6",
      promptOverlay: "rgba(224, 94, 0, 0.52)",
      buttonBorder: "#E2E8E2",
      addressActionBackground: "#FFF1E6",
      addressActionText: "#FF6A00",
      liveLocationBlue: "#FF6A00",
    },
    productDetail: {
      pageBackground:
        "bg-white dark:bg-[#E05E00]",
      primaryBadge: "bg-[#FF6A00] text-white",
      priceText: "text-[#FF6A00]",
      breadcrumbHover: "hover:text-[#FF6A00]",
      quantityBorder: "border-[#FF6A00]",
      quantityHover: "hover:bg-[#FFF1E6]",
      primaryButton: "bg-[#FF6A00] hover:bg-[#E05E00] text-white",
      categoryBadge: "bg-[#FFF1E6] text-[#FF6A00] border-[#E2E8E2]",
    },
    notifications: {
      headerIcon: "#FF6A00",
      countBadge: "#FF6A00",
      unreadDot: "#FF6A00",
      unreadBackground: "bg-green-50/70 dark:bg-green-950/20 border-green-200 dark:border-green-900/50",
      readBackground: "bg-white dark:bg-[#1A2421] border-gray-200 dark:border-gray-800",
      offerIcon: "text-[#FF6A00]",
      broadcastIcon: "text-[#FF6A00]",
    },
    wallet: {
      pageBackground: "bg-white dark:bg-[#E05E00]",
      headerSurface: "bg-white dark:bg-[#1A2421]",
      brandGradient: "linear-gradient(145deg, #FF6A00, #E05E00)",
      brandShadow: "rgba(9, 36, 29, 0.28)",
      refundText: "text-[#FF6A00] dark:text-orange-300",
      filterActive:
        "bg-white dark:bg-[#1A2421] border-2 border-[#FF6A00] dark:border-orange-400 text-[#FF6A00] dark:text-orange-300 shadow-sm",
      addMoneyButton:
        "bg-[#FF6A00] hover:bg-[#E05E00] text-white",
    },
    cart: {
      pageBackground:
        "bg-white dark:bg-[#E05E00]",
      primaryText: "#FF6A00",
      primarySurface: "#FFF1E6",
      primaryBorder: "#FF6A00",
      primaryButton: "bg-[#FF6A00] hover:bg-[#E05E00] text-white",
      primaryButtonAlt: "bg-white border border-[#FF6A00] text-[#FF6A00] hover:bg-orange-50",
      pillSurface: "bg-orange-50 text-[#FF6A00] border border-orange-100",
      paymentSelected:
        "border-[#FF6A00] bg-[#FF6A00] shadow-lg shadow-orange-500/30",
      paymentHover:
        "hover:border-orange-200 dark:hover:border-orange-900/30",
      progressGradient: "linear-gradient(90deg, #FF6A00, #E05E00)",
      successShadow: "shadow-orange-200/70 dark:shadow-orange-950/40",
    },
    orders: {
      primaryText: "#FF6A00",
      primaryButton: "bg-[#FF6A00] hover:bg-[#E05E00] text-white",
      primaryButtonAlt: "bg-white border border-[#FF6A00] text-[#FF6A00] hover:bg-orange-50",
      primaryGradient: "linear-gradient(135deg, #FF6A00 0%, #E05E00 100%)",
      softSurface: "bg-orange-50 border-orange-100 text-[#FF6A00]",
      focusRing: "#FF6A00",
    },
    profile: {
      pageBackground:
        "bg-white dark:bg-[#E05E00]",
      sectionAccent: "#FF6A00",
      accentBar: "bg-[#FF6A00]",
      avatarBackground: "#FF6A00",
      avatarSurface: "bg-[#FF6A00]",
      avatarEditButton: "bg-[#FF6A00] hover:bg-[#E05E00] text-white",
      fieldFocus: "#FF6A00",
      surface: "bg-white dark:bg-[#1A2421]",
      surfaceAlt: "bg-slate-50 dark:bg-slate-800/60",
      border: "border-gray-200 dark:border-gray-800",
      iconSurface: "bg-slate-100 dark:bg-slate-800",
      iconText: "text-slate-700 dark:text-slate-300",
      activeTab: "border-[#FF6A00] text-[#FF6A00]",
      primaryButton: "bg-[#FF6A00] hover:bg-[#E05E00] text-white",
      primaryButtonSoft:
        "bg-orange-50 text-[#FF6A00] border border-orange-100 hover:bg-orange-100",
      secondaryButton:
        "bg-white border border-[#E2E8E2] text-slate-700 hover:bg-slate-50",
      highlightSurface: "bg-green-50 dark:bg-green-950/30 border-green-100 dark:border-green-900/50",
      warningSurface: "bg-amber-50 border-amber-200 text-amber-800",
      destructiveButton: "#FA0000",
      linkText: "text-[#FF6A00]",
      legalLinkHover: "group-hover:text-[#FF6A00] dark:group-hover:text-orange-300",
    },
    support: {
      pageBackground:
        "bg-white dark:bg-[#E05E00]",
      iconSurface: "bg-orange-50 dark:bg-orange-950/30",
      iconText: "text-[#FF6A00] dark:text-orange-300",
      heroSurface:
        "bg-gradient-to-br from-orange-50 to-slate-50 dark:from-orange-950/20 dark:to-slate-900/40 border-orange-100 dark:border-orange-900/40",
      primaryButton: "bg-[#FF6A00] hover:bg-[#E05E00] text-white",
      primaryButtonSoft:
        "bg-orange-50 text-[#FF6A00] border border-orange-100 hover:bg-orange-100",
      outlineActive: "border-[#FF6A00] text-[#FF6A00]",
      focusRing: "#FF6A00",
      ticketBadge: "bg-orange-50 text-[#FF6A00]",
      infoSurface: "bg-green-50 border-green-200 text-green-800",
    },
    legal: {
      pageBackground: "bg-white dark:bg-[#E05E00]",
      headerSurface: "bg-white/80 dark:bg-[#E05E00]/80",
      headerBorder: "border-gray-100 dark:border-gray-900",
      loader: "#FF6A00",
      link: "#FF6A00",
      cardBorder: "border-gray-50 dark:border-gray-900",
      cardSurface: "bg-white dark:bg-[#111]",
      footerText: "text-gray-400",
      brandLabel: "Iggymet Policy",
    },
    navigation: {
      surface: "bg-white dark:bg-[#1A2421]",
      border: "border-gray-200 dark:border-gray-800",
      subtleBorder: "border-gray-100 dark:border-gray-800",
      iconButtonSurface: "bg-slate-100 dark:bg-slate-800",
      iconButtonHover: "hover:bg-slate-200 dark:hover:bg-slate-700",
      icon: "text-slate-700 dark:text-slate-300",
      badgeRing: "ring-white dark:ring-gray-800",
      activeText: "text-[#FF6A00] dark:text-orange-300",
      inactiveText:
        "text-slate-500 dark:text-slate-400 hover:text-[#FF6A00] dark:hover:text-orange-300",
      indicator: "bg-[#FF6A00] dark:bg-orange-300",
      divider: "bg-slate-300 dark:bg-slate-700",
      searchSurface: "bg-slate-100 dark:bg-[#2a2a2a]",
      searchFocus:
        "focus-within:ring-2 focus-within:ring-[#FF6A00] focus-within:bg-white dark:focus-within:bg-[#1A2421] border border-transparent focus-within:border-[#FF6A00]/20",
    },
    status: {
      vegBackground: "#F0FDF4",
      vegText: "#15803D",
      vegAccent: "#16A34A",
      successBackground: "#F0FDF4",
      successText: "#15803D",
      dangerBackground: "#FEF2F2",
      dangerText: "#DC2626",
    },
    motion: {
      easing: {
        standard: "cubic-bezier(0.22, 1, 0.36, 1)",
      },
      duration: {
        fast: "180ms",
        normal: "260ms",
        slow: "420ms",
      },
      distance: {
        revealY: "20px",
        floatY: "12px",
        textY: "16px",
      },
      shadow: {
        glow: "0 18px 38px rgba(255, 106, 0, 0.18)",
      },
    },
    migration: {
      replaceOrangeWithBrandBlue: "#FF6A00",
      replaceOrangeHoverWithBrandBlueDark: "#E05E00",
      replaceOrangeSoftWithBrandBlueSoft: "#FFF1E6",
      keepSemanticGreen: "#16A34A",
    },
    searchOverlay: {
      surface: "bg-white dark:bg-[#E05E00]",
      headerSurface: "bg-white dark:bg-[#1A2421]",
      headerBorder: "border-gray-100 dark:border-gray-800",
      closeHover: "hover:bg-slate-100 dark:hover:bg-slate-800",
      closeIcon: "text-slate-700 dark:text-slate-300",
      inputSurface: "bg-white dark:bg-[#1A2421]",
      inputBorder: "border-gray-100 dark:border-gray-800",
      inputFocusBorder: "#FF6A00",
      searchIcon: "#FF6A00",
      recentChip:
        "bg-orange-50 dark:bg-orange-950/20 hover:bg-orange-100 dark:hover:bg-orange-950/30 border border-orange-100 dark:border-orange-900/50 hover:border-orange-200 dark:hover:border-orange-800 text-slate-700 dark:text-slate-300 hover:text-[#FF6A00] dark:hover:text-orange-300",
      cardSurface: "bg-white dark:bg-[#1A2421]",
      placeholderSurface: "bg-slate-100 dark:bg-slate-800",
      placeholderIcon: "text-slate-400 dark:text-slate-500",
      itemHoverText: "group-hover:text-[#FF6A00] dark:group-hover:text-orange-300",
    },
    homepage: {
      defaults: {
        exploreMoreHeading: "Explore More",
        initialFilterTab: "sort",
        allCategoryId: "all",
      },
      shared: {
        pageBackground: "bg-white dark:bg-[#E05E00]",
        surface: "bg-white dark:bg-[#1A2421]",
        surfaceAlt: "bg-slate-50 dark:bg-slate-800/50",
        border: "border-gray-100 dark:border-gray-800",
        heading: "text-slate-400 dark:text-slate-500",
        title: "text-slate-900 dark:text-white",
        bodyText: "text-slate-700 dark:text-slate-300",
        mutedText: "text-slate-500 dark:text-slate-400",
        accentText: "text-[#FF6A00]",
        accentSoft:
          "bg-[#FFF1E6] text-[#FF6A00] hover:bg-orange-100 dark:bg-orange-950/30 dark:text-orange-300",
        accentBorder: "group-hover:border-[#FF6A00]/20",
        heroDots: "bg-black/20 backdrop-blur-md border border-white/20",
        backdrop: "bg-black/40 backdrop-blur-sm",
        toast: "bg-slate-950 text-white",
        shimmerBase: "bg-slate-100 dark:bg-slate-800",
      },
      header: {
        scrolledBackground: "#FFFFFF",
        iconAccent: "#FF6A00",
        cartBadgeBackground: "#E05E00",
        searchRailGradient: "linear-gradient(180deg, #FF6A00 0%, #E05E00 100%)",
        heroOverlay:
          "bg-[linear-gradient(180deg,rgba(37,59,31,0.36),rgba(9,36,29,0.22))] shadow-[0_16px_34px_rgba(0,0,0,0.18)]",
        foodPatternTint: "#FF6A00",
      },
      desktopNav: {
        activeText: "text-[#FF6A00] dark:text-orange-300",
        inactiveText:
          "text-gray-600 dark:text-gray-400 hover:text-[#FF6A00] dark:hover:text-orange-300",
        indicator: "bg-[#FF6A00] dark:bg-orange-300",
        searchFocus:
          "focus-within:ring-2 focus-within:ring-[#FF6A00] focus-within:bg-white dark:focus-within:bg-[#1A2421] border border-transparent focus-within:border-[#FF6A00]/20",
      },
      home: {
        stickyHeaderScrollColor: "#FFFFFF",
        chipHoverBorder: "group-hover:border-[#FF6A00]",
        chipMoreBackground: "bg-orange-50 dark:bg-orange-950/40",
        chipMoreBorder: "border-orange-100 group-hover:border-[#FF6A00]",
        chipMoreIcon: "text-[#FF6A00]",
        promoBadgeBackground: "#FF6A00",
        promoBadgeText: "#FF6A00",
        promoAccentText: "text-[#FF6A00]",
        promoAccentFill: "fill-[#FF6A00]",
        exploreHoverBorder: "group-hover:border-[#FF6A00]/30",
        exploreHoverGlow:
          "group-hover:shadow-[inset_0_0_0_1px_rgba(37,59,31,0.22)]",
        exploreOverlayPalette: [
          "from-green-500 to-emerald-500",
          "from-green-500 to-teal-500",
          "from-lime-500 to-green-600",
        ],
        restaurantCard: {
          featuredDishBadge:
            "bg-[linear-gradient(135deg,rgba(9,36,29,0.82),rgba(37,59,31,0.76))] backdrop-blur-lg text-white border border-white/20",
          bookmarkActive: "bg-[#FF6A00] text-white",
          bookmarkIdle:
            "bg-white/90 backdrop-blur-sm text-gray-800 hover:bg-white hover:text-[#FF6A00]",
          nameHover: "group-hover:text-[#FF6A00]",
          closingBadge:
            "bg-orange-50 text-[#FF6A00] border border-orange-100 dark:bg-orange-950/40 dark:text-orange-200 dark:border-orange-900/60",
          ratingActive: "bg-[#16A34A] text-white",
          ratingIdle: "bg-[#FFF1E6] text-[#FF6A00] border border-[#FFD7B8]",
          metaIcon: "text-[#FF6A00] dark:text-orange-300",
          offerIcon: "text-amber-500",
          offerText: "text-gray-700 dark:text-gray-300",
        },
        promoCards: {
          offersGradient: "linear-gradient(145deg, #FF6A00, #E05E00)",
          offersShadow: "rgba(37,59,31,0.30)",
          pureVegEnabledGradient: "linear-gradient(145deg, #E05E00, #FF6A00)",
          pureVegDisabledGradient: "linear-gradient(145deg, #003322, #E05E00)",
          pureVegShadow: "rgba(9,36,29,0.35)",
          under250Gradient: "linear-gradient(145deg, #FF6A00, #E05E00)",
          under250Shadow: "rgba(37,59,31,0.30)",
          combosGradient: "linear-gradient(145deg, #E05E00, #003322)",
          combosShadow: "rgba(9,36,29,0.32)",
          innerSurface: "rgba(255,255,255,0.14)",
        },
      },
      filters: {
        clearAllText: "text-[#FF6A00]",
        sidebarActive: "bg-white dark:bg-[#1A2421] text-[#FF6A00]",
        sidebarIndicator: "bg-[#FF6A00]",
        activeCard: "border-[#FF6A00] bg-[#FFF1E6] dark:bg-orange-950/30",
        inactiveCard:
          "border-gray-200 dark:border-gray-800 hover:border-[#FF6A00]",
        activeText: "text-[#FF6A00]",
        activeIcon: "text-[#FF6A00]",
        activeIconFill: "text-[#FF6A00] fill-[#FF6A00]",
        primaryButton: "bg-[#FF6A00] text-white hover:bg-[#E05E00]",
      },
    },
  },
  gradients: {
    primary: "linear-gradient(135deg, #FF6A00 0%, #E05E00 100%)",
    hero: "linear-gradient(180deg, #FFFFFF 0%, #FFFFFF 100%)",
    accent: "linear-gradient(135deg, #FF8A33 0%, #FF6A00 100%)",
  },
};

export default BRAND_THEME;
